apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCSPlrPBqAu1cQTG2yI4IUQVEdYXgrhzOUl0RQQFopSTBbutJ3bi/9oMUKdE5tA3KNtdvYWQnMTEIedJpx8UEUopE3La+jbgm+qD33Ywh9T2dw7++4i0BSx5NafpWqsCS4H0gVa02FhfZmFEzd92/JWwazGwEGKxwLq036tPe9aN4hvVzF0KF++jzs9GO4DVotR5aKur+cjC/I1adrnSamKyPEZR7BdyQQb4+YjmsIl8jrP0M/GRhd40l2sGG+IWh6RPUhCLhgkpdoIElDvpKnZfbNVK5iGt2jbUhd6UwRDDSFGUvGqYCFFSiNVng3zuxqmosWCnsPE2IOhTix5NJNOp18mLDp0AGvhUMMvcg48UOGb4mknQfhnKlzfXUB/ImKM9SPqMTSmk5E7QVKosRGDHRxhvmkdGPzCNtYfNMUscoerOJKe5fC9RLK1a0GSYMbyu1E07rAdsWC2bjjD/bj9oZLgl+LG9tnEGCOG0rGRL5o9Z5MhHNSk3NZikgxDSciFmobs8YIC8a4fvETRf7xjLwdNiVCihR/vPtyQk5uL185ZQikj5r9u33L/vQ7bgbayfMkODcSAsAD7fXPiDeLHqciQQmKvOwMGIW23gEAWVqTI7AiTMJoi58pWdqL+fNAjSwj1I/OEVdQlbSI/wj1plM4Pqn+rnjuY2Zf+1hUa+qaA8PcmO7U3djQr4hINHoZUYNLiCPDs6Bx3j/oDMS8ZvHK1PIc1wklA6g+r7HMsfx6hQqysdzWvc7fA19r59a71RKXRbstTAwbKQE9F3gloyt9izt+gfQL+O8NYThmup7VhjJO6PuJR9/UbVh+rwV/vayKhZACRha8or54dTEreXcLxL7KL9eINIhki3Vva8d4NjPmVVJssQbV8NAbPRdjuM7ioB3cVEQNpIY7NtD1+jk6dwEHe/wCozH6X1r7N
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
status: {}
