apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCFDuIpAJA5alE8HtNM2sQVIvq5e7VHxmstoQZfwjEuHRsMJ/5Y0aN5/5k8GINHTtdtJ9AT7V1t0n33Cod7pxhCwcR7b/jFQwrkooO+oA5rvyyXWjOIZEdANfirG8NdDnhK8Eno2PzqP86+zQPCearGLSkSN3VG8afGzeqqRNSoDgcwho21kzQaYKsqbGxQ2kWq4A5zGlK+O+Gi1igGiCBIfPc1cjlZBHj3oRwy8vLUEg0x70RUNV7ucWU7yiKMjAdT6O7kjbVPVkxoCIsGVyL4Bop4DfJNFyYVK2QdNEElCd5E/LKLlcTizh1w7ouMXaGjn77iYxUsKzmHE6bq+Yef/9k2DXkLO2sg8SEEC1KsEPZaTsFlaTiKC3cRq4DAfRURTL0pCfwF+ChAgl5nD8JX+H2FQvRsPFg9wwPP2ZVD8GI5VIydvsFbVau42MPA0ssXQEOqWxZxTio20R0h9m3hAKufbQII/TC8rezz5QKw2xJEBB5yEjR3ML2aStcLLVGuC5GZ5mSwWKfXQeI5IKUSjN+xxN0bKxht+xORTfSosqnHDHsUU7ixf6xJ2bawVoYFI+/pbyqwVljkxjL37ZmJnyUsA6rLveRye5Fk1x+lVT1/1ATptvF+r89nRmb750oFVuWAScT2VdKyzzFoMczJm8XvJ+xnlym4D1MBr+fGlRxQ4v2mWmjVZ0w19DM9OpeEcqs=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
