apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB5T1/66cob7pkOY6rvR25cJL63X7vGFOsN0RadZ7s1Maqlr38mYVLrgeE3Zsk+RaDLYdmJA4EzUmvlswHXG/oB5Obs1NJELjVPmtkRUvWZ84Jv5PFxiL2M+u2eroyTs5az6eeFt9J8b1Mgw3sP2Gkxy9y+NMlFLN/c5yNf+JDohp4JtN9lcowOs5YPNpGIe1NxCghP/MLZY7+wMZXnjXTsBby47b4Rle+Va+S68ygNVhTDUUvU4YWpt9iN3k7SuZTJnfEZWNz5Ew4NdpTTG5B5QEJmktGMBKVAo1eWkkM2O/SiKEexM9+TUyiPvkJ/rzEYCNn46W11Y70Ba1Xvj3vUKj+EV+nYXG5Q+XTMaufgCZDDHLxjwiSo0g65FJo/6QYabzzoscPq7/Je5KqZhtP2ZJqT9veBTIPCo/v8dk4yql4qywq+3VL/d2Y3UnsmtenVlQMCI0eyhVy0968vTgDzYMdNOMB0a8fosvPxMbrP4WrOWWrnm49XHSECBnveNqoF0cdWzhpJhErRBA6qXpKB6XhADOFxmwWQalkP0AGGtnXF/0GK2BcHQuUHoBOIOY0PV9KiNyK+ppKyagqpTfUKEQm2330BvI0etRmaES7DNsJU6yqHmX+qLJR7isZxDDTC2ILXk5rxMAaAx6XGTKCVTinEolze+/0uX0CB33ulcvfVXz6ikjhm9egDKdmV2HJZJM4=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
